# Generated by Django 2.1.10 on 2019-08-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0002_switch_to_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='total_btc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
